branch-defaults:
  default:
    environment: node-backend
    group_suffix: null
  master:
    environment: node-backend
    group_suffix: null
environment-defaults:
  node-backend:
    branch: null
    repository: null
global:
  application_name: messages
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
